import React, { createContext, useContext, useState, ReactNode } from 'react';
import { translationService } from '@/services/translationService';

export type Language = 'en' | 'es' | 'fr' | 'de';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (text: string) => Promise<string>;
  tSync: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    'nav.products': 'Products',
    'nav.support': 'Support',
    'nav.healthcare': 'Healthcare Professionals',
    'nav.signin': 'Sign In',
    'hero.title': 'Advanced Diabetes Management',
    'hero.subtitle': 'Experience freedom with automated insulin delivery',
    'hero.cta': 'Get Started',
    'features.monitoring': 'Real-time Monitoring',
    'features.delivery': 'Automated Insulin Delivery',
    'features.sharing': 'Data Sharing with Providers',
    'features.mobile': 'Mobile Connectivity',
    'landing.learnMore': 'Learn More',
    'landing.feature.monitoring.desc': 'Track glucose levels continuously with advanced CGM integration',
    'landing.feature.delivery.desc': "Smart insulin delivery that adapts to your body's needs",
    'landing.feature.sharing.desc': 'Share real-time data with your healthcare team',
    'landing.feature.mobile.desc': 'Stay connected with mobile app integration',
    'landing.features.title': 'Comprehensive Diabetes Management',
    'landing.features.subtitle': 'Experience the most advanced insulin pump system with features designed for your lifestyle',
    'landing.stats.timeInRange': 'Time in Range',
    'landing.stats.activeUsers': 'Active Users',
    'landing.stats.monitoring': 'Continuous Monitoring',
    'landing.stats.rating': 'User Rating',
    'landing.howItWorks.title': 'How It Works',
    'landing.howItWorks.subtitle': 'Get started with MiniMed in three simple steps',
    'landing.howItWorks.step1.title': 'Connect Your Device',
    'landing.howItWorks.step1.desc': 'Pair your MiniMed 780G pump and Guardian sensor with the dashboard for seamless data sync',
    'landing.howItWorks.step2.title': 'Monitor & Adjust',
    'landing.howItWorks.step2.desc': 'View real-time glucose trends, insulin delivery, and get personalized insights to optimize your management',
    'landing.howItWorks.step3.title': 'Share with Your Team',
    'landing.howItWorks.step3.desc': 'Grant your healthcare provider secure access to your data for better-informed treatment decisions',
    'landing.testimonials.title': 'What Our Users Say',
    'landing.testimonials.subtitle': 'Hear from patients and healthcare providers who trust MiniMed',
    'landing.testimonial1.name': 'Sarah M.',
    'landing.testimonial1.role': 'Type 1 Diabetes Patient',
    'landing.testimonial1.quote': 'The MiniMed 780G has completely changed how I manage my diabetes. My time in range improved from 60% to over 90% in just weeks.',
    'landing.testimonial2.name': 'Dr. James W.',
    'landing.testimonial2.role': 'Endocrinologist',
    'landing.testimonial2.quote': 'The data sharing features allow me to make more informed decisions for my patients. The dashboard gives a comprehensive view I can trust.',
    'landing.testimonial3.name': 'Maria L.',
    'landing.testimonial3.role': 'Parent of T1D Child',
    'landing.testimonial3.quote': 'As a parent, being able to monitor my child\'s glucose levels remotely gives me incredible peace of mind. This system is a game changer.',
    'landing.faq.title': 'Frequently Asked Questions',
    'landing.faq.subtitle': 'Find answers to common questions about MiniMed',
    'landing.faq1.question': 'What is the MiniMed 780G system?',
    'landing.faq1.answer': 'The MiniMed 780G is an advanced hybrid closed-loop insulin pump system that automatically adjusts basal insulin delivery based on continuous glucose monitor readings, helping to keep glucose levels in your target range.',
    'landing.faq2.question': 'How does the automatic insulin delivery work?',
    'landing.faq2.answer': 'The system uses SmartGuard technology to read your glucose levels every 5 minutes and automatically adjusts your basal insulin delivery. It can increase, decrease, or suspend insulin delivery to help prevent highs and lows.',
    'landing.faq3.question': 'Can I share my data with my healthcare provider?',
    'landing.faq3.answer': 'Yes! The MiniMed Dashboard allows you to grant secure access to your healthcare provider. They can view your glucose trends, insulin delivery history, and daily summaries to help optimize your treatment plan.',
    'landing.faq4.question': 'Is the dashboard available on mobile devices?',
    'landing.faq4.answer': 'The MiniMed Dashboard is a responsive web application that works on smartphones, tablets, and desktop computers. You can access your data anywhere with an internet connection.',
    'landing.cta.title': 'Ready to Take Control?',
    'landing.cta.subtitle': 'Join thousands of users who have transformed their diabetes management with MiniMed',
    'landing.cta.button': 'Start Your Journey',
    'landing.cta.benefit1': 'Free demo account',
    'landing.cta.benefit2': 'No credit card required',
    'landing.cta.benefit3': '24/7 support available',
  },
  es: {
    'nav.products': 'Productos',
    'nav.support': 'Soporte',
    'nav.healthcare': 'Profesionales de la Salud',
    'nav.signin': 'Iniciar Sesión',
    'hero.title': 'Gestión Avanzada de la Diabetes',
    'hero.subtitle': 'Experimente la libertad con la administración automatizada de insulina',
    'hero.cta': 'Comenzar',
    'features.monitoring': 'Monitoreo en Tiempo Real',
    'features.delivery': 'Administración Automatizada de Insulina',
    'features.sharing': 'Compartir Datos con Proveedores',
    'features.mobile': 'Conectividad Móvil',
    'landing.learnMore': 'Más Información',
    'landing.feature.monitoring.desc': 'Seguimiento continuo de los niveles de glucosa con integración avanzada de MCG',
    'landing.feature.delivery.desc': 'Administración inteligente de insulina que se adapta a las necesidades de su cuerpo',
    'landing.feature.sharing.desc': 'Comparta datos en tiempo real con su equipo de atención médica',
    'landing.feature.mobile.desc': 'Manténgase conectado con la integración de la aplicación móvil',
    'landing.features.title': 'Gestión Integral de la Diabetes',
    'landing.features.subtitle': 'Experimente el sistema de bomba de insulina más avanzado con funciones diseñadas para su estilo de vida',
    'landing.stats.timeInRange': 'Tiempo en Rango',
    'landing.stats.activeUsers': 'Usuarios Activos',
    'landing.stats.monitoring': 'Monitoreo Continuo',
    'landing.stats.rating': 'Calificación de Usuarios',
    'landing.howItWorks.title': 'Cómo Funciona',
    'landing.howItWorks.subtitle': 'Comience con MiniMed en tres sencillos pasos',
    'landing.howItWorks.step1.title': 'Conecte Su Dispositivo',
    'landing.howItWorks.step1.desc': 'Empareje su bomba MiniMed 780G y sensor Guardian con el panel para una sincronización perfecta',
    'landing.howItWorks.step2.title': 'Monitoree y Ajuste',
    'landing.howItWorks.step2.desc': 'Vea tendencias de glucosa en tiempo real, administración de insulina y obtenga información personalizada',
    'landing.howItWorks.step3.title': 'Comparta con Su Equipo',
    'landing.howItWorks.step3.desc': 'Otorgue a su proveedor de atención médica acceso seguro a sus datos para decisiones de tratamiento mejor informadas',
    'landing.testimonials.title': 'Lo Que Dicen Nuestros Usuarios',
    'landing.testimonials.subtitle': 'Escuche a pacientes y proveedores de atención médica que confían en MiniMed',
    'landing.testimonial1.name': 'Sarah M.',
    'landing.testimonial1.role': 'Paciente con Diabetes Tipo 1',
    'landing.testimonial1.quote': 'El MiniMed 780G ha cambiado completamente cómo manejo mi diabetes. Mi tiempo en rango mejoró del 60% a más del 90% en solo semanas.',
    'landing.testimonial2.name': 'Dr. James W.',
    'landing.testimonial2.role': 'Endocrinólogo',
    'landing.testimonial2.quote': 'Las funciones de compartir datos me permiten tomar decisiones más informadas para mis pacientes. El panel brinda una vista integral en la que puedo confiar.',
    'landing.testimonial3.name': 'María L.',
    'landing.testimonial3.role': 'Madre de Niño con DT1',
    'landing.testimonial3.quote': 'Como madre, poder monitorear los niveles de glucosa de mi hijo de forma remota me da una increíble tranquilidad. Este sistema es revolucionario.',
    'landing.faq.title': 'Preguntas Frecuentes',
    'landing.faq.subtitle': 'Encuentre respuestas a preguntas comunes sobre MiniMed',
    'landing.faq1.question': '¿Qué es el sistema MiniMed 780G?',
    'landing.faq1.answer': 'El MiniMed 780G es un sistema avanzado de bomba de insulina de circuito cerrado híbrido que ajusta automáticamente la administración de insulina basal según las lecturas del monitor continuo de glucosa.',
    'landing.faq2.question': '¿Cómo funciona la administración automática de insulina?',
    'landing.faq2.answer': 'El sistema utiliza la tecnología SmartGuard para leer sus niveles de glucosa cada 5 minutos y ajusta automáticamente su administración de insulina basal.',
    'landing.faq3.question': '¿Puedo compartir mis datos con mi proveedor de atención médica?',
    'landing.faq3.answer': '¡Sí! El Panel de MiniMed le permite otorgar acceso seguro a su proveedor de atención médica para ver sus tendencias de glucosa e historial de insulina.',
    'landing.faq4.question': '¿El panel está disponible en dispositivos móviles?',
    'landing.faq4.answer': 'El Panel de MiniMed es una aplicación web responsiva que funciona en teléfonos inteligentes, tabletas y computadoras de escritorio.',
    'landing.cta.title': '¿Listo para Tomar el Control?',
    'landing.cta.subtitle': 'Únase a miles de usuarios que han transformado su manejo de la diabetes con MiniMed',
    'landing.cta.button': 'Comience Su Viaje',
    'landing.cta.benefit1': 'Cuenta demo gratuita',
    'landing.cta.benefit2': 'No se requiere tarjeta de crédito',
    'landing.cta.benefit3': 'Soporte disponible 24/7',
  },
  fr: {
    'nav.products': 'Produits',
    'nav.support': 'Support',
    'nav.healthcare': 'Professionnels de Santé',
    'nav.signin': 'Se Connecter',
    'hero.title': 'Gestion Avancée du Diabète',
    'hero.subtitle': "Découvrez la liberté avec l'administration automatisée d'insuline",
    'hero.cta': 'Commencer',
    'features.monitoring': 'Surveillance en Temps Réel',
    'features.delivery': "Administration Automatisée d'Insuline",
    'features.sharing': 'Partage de Données avec les Prestataires',
    'features.mobile': 'Connectivité Mobile',
    'landing.learnMore': 'En Savoir Plus',
    'landing.feature.monitoring.desc': 'Suivi continu des niveaux de glucose avec intégration avancée du CGM',
    'landing.feature.delivery.desc': "Administration intelligente d'insuline qui s'adapte aux besoins de votre corps",
    'landing.feature.sharing.desc': 'Partagez des données en temps réel avec votre équipe soignante',
    'landing.feature.mobile.desc': "Restez connecté avec l'intégration de l'application mobile",
    'landing.features.title': 'Gestion Complète du Diabète',
    'landing.features.subtitle': "Découvrez le système de pompe à insuline le plus avancé avec des fonctionnalités conçues pour votre mode de vie",
    'landing.stats.timeInRange': 'Temps dans la Cible',
    'landing.stats.activeUsers': 'Utilisateurs Actifs',
    'landing.stats.monitoring': 'Surveillance Continue',
    'landing.stats.rating': 'Note des Utilisateurs',
    'landing.howItWorks.title': 'Comment Ça Marche',
    'landing.howItWorks.subtitle': 'Démarrez avec MiniMed en trois étapes simples',
    'landing.howItWorks.step1.title': 'Connectez Votre Appareil',
    'landing.howItWorks.step1.desc': 'Associez votre pompe MiniMed 780G et votre capteur Guardian au tableau de bord pour une synchronisation transparente',
    'landing.howItWorks.step2.title': 'Surveillez et Ajustez',
    'landing.howItWorks.step2.desc': "Consultez les tendances glycémiques en temps réel, l'administration d'insuline et obtenez des informations personnalisées",
    'landing.howItWorks.step3.title': 'Partagez avec Votre Équipe',
    'landing.howItWorks.step3.desc': "Accordez à votre prestataire de soins un accès sécurisé à vos données pour des décisions de traitement mieux éclairées",
    'landing.testimonials.title': 'Ce Que Disent Nos Utilisateurs',
    'landing.testimonials.subtitle': 'Écoutez les patients et les professionnels de santé qui font confiance à MiniMed',
    'landing.testimonial1.name': 'Sarah M.',
    'landing.testimonial1.role': 'Patiente Diabétique de Type 1',
    'landing.testimonial1.quote': "Le MiniMed 780G a complètement changé ma gestion du diabète. Mon temps dans la cible est passé de 60% à plus de 90% en quelques semaines.",
    'landing.testimonial2.name': 'Dr. James W.',
    'landing.testimonial2.role': 'Endocrinologue',
    'landing.testimonial2.quote': "Les fonctionnalités de partage de données me permettent de prendre des décisions plus éclairées pour mes patients. Le tableau de bord offre une vue complète et fiable.",
    'landing.testimonial3.name': 'Maria L.',
    'landing.testimonial3.role': "Parent d'Enfant DT1",
    'landing.testimonial3.quote': "En tant que parent, pouvoir surveiller à distance les niveaux de glucose de mon enfant me donne une tranquillité d'esprit incroyable.",
    'landing.faq.title': 'Questions Fréquentes',
    'landing.faq.subtitle': 'Trouvez des réponses aux questions courantes sur MiniMed',
    'landing.faq1.question': "Qu'est-ce que le système MiniMed 780G ?",
    'landing.faq1.answer': "Le MiniMed 780G est un système avancé de pompe à insuline en boucle fermée hybride qui ajuste automatiquement l'administration d'insuline basale.",
    'landing.faq2.question': "Comment fonctionne l'administration automatique d'insuline ?",
    'landing.faq2.answer': "Le système utilise la technologie SmartGuard pour lire vos niveaux de glucose toutes les 5 minutes et ajuste automatiquement votre administration d'insuline basale.",
    'landing.faq3.question': 'Puis-je partager mes données avec mon prestataire de soins ?',
    'landing.faq3.answer': "Oui ! Le Tableau de Bord MiniMed vous permet d'accorder un accès sécurisé à votre prestataire de soins pour consulter vos tendances glycémiques.",
    'landing.faq4.question': 'Le tableau de bord est-il disponible sur les appareils mobiles ?',
    'landing.faq4.answer': "Le Tableau de Bord MiniMed est une application web responsive qui fonctionne sur smartphones, tablettes et ordinateurs.",
    'landing.cta.title': 'Prêt à Prendre le Contrôle ?',
    'landing.cta.subtitle': 'Rejoignez des milliers d\'utilisateurs qui ont transformé leur gestion du diabète avec MiniMed',
    'landing.cta.button': 'Commencez Votre Parcours',
    'landing.cta.benefit1': 'Compte démo gratuit',
    'landing.cta.benefit2': 'Aucune carte de crédit requise',
    'landing.cta.benefit3': 'Support disponible 24/7',
  },
  de: {
    'nav.products': 'Produkte',
    'nav.support': 'Unterstützung',
    'nav.healthcare': 'Gesundheitsfachkräfte',
    'nav.signin': 'Anmelden',
    'hero.title': 'Fortgeschrittenes Diabetes-Management',
    'hero.subtitle': 'Erleben Sie Freiheit mit automatisierter Insulinabgabe',
    'hero.cta': 'Loslegen',
    'features.monitoring': 'Echtzeitüberwachung',
    'features.delivery': 'Automatisierte Insulinabgabe',
    'features.sharing': 'Datenaustausch mit Anbietern',
    'features.mobile': 'Mobile Konnektivität',
    'landing.learnMore': 'Mehr Erfahren',
    'landing.feature.monitoring.desc': 'Kontinuierliche Verfolgung der Glukosewerte mit fortschrittlicher CGM-Integration',
    'landing.feature.delivery.desc': 'Intelligente Insulinabgabe, die sich an die Bedürfnisse Ihres Körpers anpasst',
    'landing.feature.sharing.desc': 'Teilen Sie Echtzeitdaten mit Ihrem Gesundheitsteam',
    'landing.feature.mobile.desc': 'Bleiben Sie mit der mobilen App-Integration verbunden',
    'landing.features.title': 'Umfassendes Diabetes-Management',
    'landing.features.subtitle': 'Erleben Sie das fortschrittlichste Insulinpumpensystem mit Funktionen für Ihren Lebensstil',
    'landing.stats.timeInRange': 'Zeit im Zielbereich',
    'landing.stats.activeUsers': 'Aktive Benutzer',
    'landing.stats.monitoring': 'Kontinuierliche Überwachung',
    'landing.stats.rating': 'Benutzerbewertung',
    'landing.howItWorks.title': 'So Funktioniert Es',
    'landing.howItWorks.subtitle': 'Starten Sie mit MiniMed in drei einfachen Schritten',
    'landing.howItWorks.step1.title': 'Gerät Verbinden',
    'landing.howItWorks.step1.desc': 'Koppeln Sie Ihre MiniMed 780G Pumpe und Guardian Sensor mit dem Dashboard für nahtlose Datensynchronisation',
    'landing.howItWorks.step2.title': 'Überwachen und Anpassen',
    'landing.howItWorks.step2.desc': 'Sehen Sie Echtzeit-Glukosetrends, Insulinabgabe und erhalten Sie personalisierte Einblicke',
    'landing.howItWorks.step3.title': 'Mit Ihrem Team Teilen',
    'landing.howItWorks.step3.desc': 'Gewähren Sie Ihrem Gesundheitsdienstleister sicheren Zugriff auf Ihre Daten für besser informierte Behandlungsentscheidungen',
    'landing.testimonials.title': 'Was Unsere Benutzer Sagen',
    'landing.testimonials.subtitle': 'Hören Sie von Patienten und Gesundheitsdienstleistern, die MiniMed vertrauen',
    'landing.testimonial1.name': 'Sarah M.',
    'landing.testimonial1.role': 'Typ-1-Diabetes-Patientin',
    'landing.testimonial1.quote': 'Das MiniMed 780G hat mein Diabetes-Management komplett verändert. Meine Zeit im Zielbereich verbesserte sich von 60% auf über 90% in nur Wochen.',
    'landing.testimonial2.name': 'Dr. James W.',
    'landing.testimonial2.role': 'Endokrinologe',
    'landing.testimonial2.quote': 'Die Datenaustausch-Funktionen ermöglichen mir fundiertere Entscheidungen für meine Patienten. Das Dashboard bietet eine umfassende und vertrauenswürdige Übersicht.',
    'landing.testimonial3.name': 'Maria L.',
    'landing.testimonial3.role': 'Mutter eines T1D-Kindes',
    'landing.testimonial3.quote': 'Als Mutter gibt mir die Möglichkeit, die Glukosewerte meines Kindes aus der Ferne zu überwachen, unglaubliche Sicherheit. Dieses System ist bahnbrechend.',
    'landing.faq.title': 'Häufig Gestellte Fragen',
    'landing.faq.subtitle': 'Finden Sie Antworten auf häufige Fragen zu MiniMed',
    'landing.faq1.question': 'Was ist das MiniMed 780G System?',
    'landing.faq1.answer': 'Das MiniMed 780G ist ein fortschrittliches Hybrid-Closed-Loop-Insulinpumpensystem, das die Basalinsulinabgabe automatisch anpasst.',
    'landing.faq2.question': 'Wie funktioniert die automatische Insulinabgabe?',
    'landing.faq2.answer': 'Das System verwendet die SmartGuard-Technologie, um Ihre Glukosewerte alle 5 Minuten zu lesen und passt Ihre Basalinsulinabgabe automatisch an.',
    'landing.faq3.question': 'Kann ich meine Daten mit meinem Gesundheitsdienstleister teilen?',
    'landing.faq3.answer': 'Ja! Das MiniMed Dashboard ermöglicht Ihnen, Ihrem Gesundheitsdienstleister sicheren Zugriff zu gewähren, um Ihre Glukosetrends und Insulinhistorie einzusehen.',
    'landing.faq4.question': 'Ist das Dashboard auf mobilen Geräten verfügbar?',
    'landing.faq4.answer': 'Das MiniMed Dashboard ist eine responsive Webanwendung, die auf Smartphones, Tablets und Desktop-Computern funktioniert.',
    'landing.cta.title': 'Bereit, die Kontrolle zu Übernehmen?',
    'landing.cta.subtitle': 'Schließen Sie sich Tausenden von Benutzern an, die ihr Diabetes-Management mit MiniMed transformiert haben',
    'landing.cta.button': 'Starten Sie Ihre Reise',
    'landing.cta.benefit1': 'Kostenloses Demo-Konto',
    'landing.cta.benefit2': 'Keine Kreditkarte erforderlich',
    'landing.cta.benefit3': '24/7 Support verfügbar',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = async (text: string): Promise<string> => {
    if (language === 'en') {
      return text;
    }
    return await translationService.translate(text, language, 'en');
  };

  const tSync = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, tSync }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
